name = "SparseStates"
uuid = "7b3b5571-cbe6-48f0-b949-c5e943b6334f"
authors = ["Giacomo Giudice <giacomo.giudice@mail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1"
