name = "SparseStates"
uuid = "7b3b5571-cbe6-48f0-b949-c5e943b6334f"
authors = ["Giacomo Giudice <giacomo.giudice@mail.com>"]
version = "0.1.0"

[deps]
BitPermutations = "81206824-6155-40a8-95f7-18696067be4d"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RationalRoots = "308eb6b3-cc68-5ff3-9e97-c3c4da4fa681"

[compat]
BitPermutations = "0.3.0"
Combinatorics = "1.0.2"
LinearAlgebra = "1.11.0"
RationalRoots = "0.2.1"
