name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


# Needed to allow `julia-actions/cache` to delete old caches
permissions:
  actions: write
  contents: read

jobs:
  build:
    name: Julia ${{ matrix.julia-version }}
    needs: style-check
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.10','1.12','nightly'] # earliest, lts, stable, nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          show-versioninfo: true
      
      - name: Cache
        uses: julia-actions/cache@v2

      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1
        
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
  style-check:
    name: Style check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1' # Latest stable version

      - name: Cache
        uses: julia-actions/cache@v2

      - name: Run JuliaFormatter
        run: |
          using Pkg
          Pkg.add("JuliaFormatter")

          using JuliaFormatter
          formatted = JuliaFormatter.format(".", verbose=true)

          if formatted
            @info "All files match designated style"
            exit(0)
          else
            @error "Some files do not match the designated style"
            write(stdout, read(`git diff`, String))
            exit(1)
          end
        shell: julia --color=yes --compiled-modules=no --optimize=0 {0}
